language: python

python:
    - "2.7"

env:
  global:
    - PORT=5000
    - HOST=0.0.0.0
    - DEBUG=TRUE
    - PG_HOST=127.0.0.1
    - PG_PORT=5432
    - PG_USER=postgres
    - PG_PASSWORD=
    - PG_DB=travis_test
    - PG_LIMIT=250
    - PG_DEFAULT=20

install: "pip install -r config/requirements.txt"

services: postgresql

before_script:
    - psql -c 'create database travis_test;' -U postgres
    - psql travis_test < dev/dev_dump.sql -U postgres

script: nosetests -v data/tests/
